badging/badging/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('users.urls')),
]

badging/users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
	path('', views.index, name='index'),
	path('<int:person_id>/', views.detail, name='detail'),
	path('<int:person_id>/badge/', views.badge, name='badge'),
	path('<int:person_id>/add_badge/', views.add_badge, name='add_badge'),
	path('add_person', views.add_person, name='add_person'),
]

badging/users/models.py
from django.db import models

# Create your models here.
class Person(models.Model):
	name = models.CharField(max_length=100)
	#username = models.CharField(max_length=100)
	#email = models.CharField(max_length=200)
	#password = models.CharField(max_length=200)
	
	def __str__(self):
		return self.name
	
class Badge(models.Model):
	name = models.CharField(max_length=200)
	person = models.ForeignKey(Person, on_delete=models.CASCADE)
	presenter = models.CharField(max_length=200)
	#summary = models.CharField(max_length=1000)
	def __str__(self):
		return self.name

badging/users/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from django.template import loader

from .models import Person, Badge

# Create your views here.
def index(request):
	latest_person_list = Person.objects.order_by('-name')
	#template = loader.get_template('users/index.html')
	context = { 'latest_person_list' : latest_person_list, }
	return render(request, 'users/index.html', context)
	#return HttpResponse(template.render(context, request))

def detail(request, person_id):
	#try:
	#	person = Person.objects.get(pk = person_id)
	#except Person.DoesNotExist:
	#	raise Http404("Person is not in the system.")
	person = get_object_or_404(Person, pk = person_id)
	return render(request, 'users/detail.html', {'person': person})
	
def badge(request, person_id):
	person = get_object_or_404(Person, pk = person_id)
	return render(request, 'users/badge.html', {'person': person})
	
def add_person(request):
	p = Person(name = request.POST['name'])
	if len(p.name) == 0:
		latest_person_list = Person.objects.order_by('-name')
		context = { 'latest_person_list' : latest_person_list, 'error_message' : "Invalid Person Name"}		
		return render(request, 'users/index.html', context )
	else:
		latest_person_list = Person.objects.order_by('-name')
		for person in latest_person_list:
			if p.name == person.name:
				context = { 'latest_person_list' : latest_person_list, 'error_message' : "Person already exists"}
				return render(request, 'users/index.html', context)
		p.save()
		latest_person_list = Person.objects.order_by('-name')
		context = { 'latest_person_list' : latest_person_list, }
		return render(request, 'users/index.html', context)
	
def add_badge(request, person_id):
	person = get_object_or_404(Person, pk = person_id)
	#Tries and excepts must be changed so no blank badges can be entered
	b = Badge(name = request.POST['name'], presenter = request.POST['presenter'])
	if len(b.name) == 0:
		return render(request, 'users/badge.html', {
			'person': person,
			'error_message': "Invalid Badge Name.",
		})
	elif len(b.presenter) == 0:
		return render(request, 'users/badge.html', {
			'person': person,
			'error_message': "Invalid Presenter Name.",
		})
	else:
		badge_list = person.badge_set.order_by('-name')
		for badge in badge_list:
			badge_name = badge.name
			if b.name == badge_name:
				return render(request, 'users/badge.html', {
				'person': person,
				'error_message': "Badge already exists.",
				})
		person.badge_set.create(name = b.name, presenter = b.presenter)
		#print(request.POST)
		return render(request, 'users/detail.html', {'person' : person})

badging/users/templates/users/badge.html
<h1>Adding Badge</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

Badges have names and presenters
<form action="{% url 'users:add_badge' person.id %}" method="post">
{% csrf_token %}
	Name:<br>
	<input type="text" name="name" value="">
	<br>
	Presenter:<br>
	<input type="text" name="presenter" value="">
	<br>
	
	<input type="submit" value="Add" />
</form>

badging/users/templates/users/detail.html
<h1>{{ person.name }}</h1>

<h2>Badge List:</h2>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<ul>
{% for badge in person.badge_set.all %}
	<li>{{ badge.name }}</li>
{% endfor %}
</ul>

<form action="{% url 'users:badge' person.id %}">
	<input type="submit" value="Add Badge">
</form>

badging/users/templates/users/index.html
{% if latest_person_list %}
	<ul>
	{% for person in latest_person_list %}
		<li><a href="{% url 'users:detail' person.id %}">{{ person.name }}</a></li>
	{% endfor %}
	</ul>
{% else %}
	<p>No users are in the system.</p>
{% endif %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'users:add_person' %}" method="post">
{% csrf_token %}
	Name:<br>
	<input type="text" name="name" value="">
	<br>
	
	<input type="submit" value="Add" />
</form>